//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coursework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активная подборка .
        /// </summary>
        public static string ActiveCollection {
            get {
                return ResourceManager.GetString("ActiveCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новую подборку.
        /// </summary>
        public static string AddCollectionButton {
            get {
                return ResourceManager.GetString("AddCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой подборки.
        /// </summary>
        public static string AddingNewCollectionTextBlock {
            get {
                return ResourceManager.GetString("AddingNewCollectionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление слов.
        /// </summary>
        public static string AddingWords {
            get {
                return ResourceManager.GetString("AddingWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новое слово.
        /// </summary>
        public static string AddNewWord {
            get {
                return ResourceManager.GetString("AddNewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить связку.
        /// </summary>
        public static string AddPair {
            get {
                return ResourceManager.GetString("AddPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название приложения .
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная информация.
        /// </summary>
        public static string BasicInformationTextBlok {
            get {
                return ResourceManager.GetString("BasicInformationTextBlok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас остались заполненные поля. Вы действительно хотите выйти?.
        /// </summary>
        public static string CancelWithFullFields {
            get {
                return ResourceManager.GetString("CancelWithFullFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание подборки.
        /// </summary>
        public static string CollectionDescription {
            get {
                return ResourceManager.GetString("CollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название подборки.
        /// </summary>
        public static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подборки.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расскажите о себе .
        /// </summary>
        public static string CreatingNewUser {
            get {
                return ResourceManager.GetString("CreatingNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить подборку.
        /// </summary>
        public static string DeleteCollection {
            get {
                return ResourceManager.GetString("DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранные подборки.
        /// </summary>
        public static string DeleteSelectedCollections {
            get {
                return ResourceManager.GetString("DeleteSelectedCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование подборки.
        /// </summary>
        public static string EditCollection {
            get {
                return ResourceManager.GetString("EditCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас остались незаполненные поля.
        /// </summary>
        public static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровой режим.
        /// </summary>
        public static string GameModeButton {
            get {
                return ResourceManager.GetString("GameModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, друг.
        /// </summary>
        public static string HelloFriend {
            get {
                return ResourceManager.GetString("HelloFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учить слова.
        /// </summary>
        public static string LearningButton {
            get {
                return ResourceManager.GetString("LearningButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смешанный.
        /// </summary>
        public static string MixedType {
            get {
                return ResourceManager.GetString("MixedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест будет включать в себя задания как и с вариантами ответа, так и с правописанием.
        /// </summary>
        public static string MixedTypeDescription {
            get {
                return ResourceManager.GetString("MixedTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить связку.
        /// </summary>
        public static string RemovePair {
            get {
                return ResourceManager.GetString("RemovePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скажи как тебя зовут.
        /// </summary>
        public static string SayYourName {
            get {
                return ResourceManager.GetString("SayYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учить выбранные подборки.
        /// </summary>
        public static string SelectedCollectionsButton {
            get {
                return ResourceManager.GetString("SelectedCollectionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип теста .
        /// </summary>
        public static string SelectTypeOfTest {
            get {
                return ResourceManager.GetString("SelectTypeOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткая статистика.
        /// </summary>
        public static string ShotStatistics {
            get {
                return ResourceManager.GetString("ShotStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правописание .
        /// </summary>
        public static string SpellingType {
            get {
                return ResourceManager.GetString("SpellingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам будет давно слово. Необходимо правильно написать его перевод .
        /// </summary>
        public static string SpellingTypeDescription {
            get {
                return ResourceManager.GetString("SpellingTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теория.
        /// </summary>
        public static string TheoryButton {
            get {
                return ResourceManager.GetString("TheoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет ни одной коллекции. Добавьте свою первую коллекцию и возвращайтесь опять.
        /// </summary>
        public static string UserWithoutCollections {
            get {
                return ResourceManager.GetString("UserWithoutCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UserWithoutPhoto {
            get {
                object obj = ResourceManager.GetObject("UserWithoutPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, как тебя зовут? .
        /// </summary>
        public static string WhatIsYourName {
            get {
                return ResourceManager.GetString("WhatIsYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено выделенных подборок. Выделите хотя бы одну подборку .
        /// </summary>
        public static string WithoutCheckedCollections {
            get {
                return ResourceManager.GetString("WithoutCheckedCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С вариантами ответа .
        /// </summary>
        public static string WordsType {
            get {
                return ResourceManager.GetString("WordsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам будет дано слово и четыре варианта ответа, один из которых будет правильный.
        /// </summary>
        public static string WordsTypeDescription {
            get {
                return ResourceManager.GetString("WordsTypeDescription", resourceCulture);
            }
        }
    }
}
